version: '3.7'
services:
  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - docker.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - docker.env
    environment:
      DB_URI: ${DB_URI}
      DB_PORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
  server1:
    hostname: server1
    container_name: server1
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - docker.env
    ports:
      - 81:${PORT}
    depends_on:
      - redis
      - mongodb
    command: npm run start:dev
  server2:
    hostname: server2
    container_name: server2
    build:
      context: .
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - docker.env
    ports:
      - 82:${PORT}
    depends_on:
      - redis
      - mongodb
    command: npm run start:dev
  nginx:
    build:
      context: .
      dockerfile: ./DockerfileNginx
    env_file:
      - docker.env
    ports:
      - 80:80
    depends_on:
      - server1
      - server2
