version : '3'

services:
  lb:
    image: haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
  ws1:
    image: ms
    environment:
      - APPID=1111
  ws2:
    image: ms
    environment:
      - APPID=2222
  ws3:
    image: ms
    environment:
      - APPID=3333
  ws4:
    image: ms
    environment:
      - APPID=4444
  rds:
    image: redis