export default {
  ROOM_MESSAGES_LIMIT: 50,
  CLUB_CREATION_COST: 50,
  CLUB_ENTRY_COST: 100,
  CLUB_MEMBERS_LIMIT: 50,
  DONATION_REQUEST_AMOUNT: 10000,
  DONATION_REQUEST_EXPIRATION_MINUTES: 30,
  MANDATORY_MINUTES_SINCE_LAST_DONATION_REQUEST: 60,
};
